# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1051, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 330, 135, 113))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.column = QtWidgets.QLineEdit(self.layoutWidget)
        self.column.setObjectName("column")
        self.verticalLayout_3.addWidget(self.column)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.row = QtWidgets.QLineEdit(self.layoutWidget)
        self.row.setObjectName("row")
        self.verticalLayout_3.addWidget(self.row)
        self.add_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout_3.addWidget(self.add_btn)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(530, 330, 153, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.x_row = QtWidgets.QLineEdit(self.layoutWidget1)
        self.x_row.setObjectName("x_row")
        self.verticalLayout.addWidget(self.x_row)
        self.y_row = QtWidgets.QLineEdit(self.layoutWidget1)
        self.y_row.setObjectName("y_row")
        self.verticalLayout.addWidget(self.y_row)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.relation_function = QtWidgets.QLineEdit(self.layoutWidget1)
        self.relation_function.setObjectName("relation_function")
        self.horizontalLayout.addWidget(self.relation_function)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.rela_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.rela_btn.setObjectName("rela_btn")
        self.verticalLayout.addWidget(self.rela_btn)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(790, 330, 274, 95))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.x_name = QtWidgets.QLineEdit(self.layoutWidget2)
        self.x_name.setObjectName("x_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.x_name)
        self.x_index = QtWidgets.QLineEdit(self.layoutWidget2)
        self.x_index.setObjectName("x_index")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.x_index)
        self.y_name = QtWidgets.QLineEdit(self.layoutWidget2)
        self.y_name.setObjectName("y_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.y_name)
        self.y_index = QtWidgets.QLineEdit(self.layoutWidget2)
        self.y_index.setObjectName("y_index")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.y_index)
        self.exam_num = QtWidgets.QLineEdit(self.layoutWidget2)
        self.exam_num.setObjectName("exam_num")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.exam_num)
        self.anly_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.anly_btn.setObjectName("anly_btn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.anly_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(240, 331, 218, 110))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.a_line = QtWidgets.QLineEdit(self.widget)
        self.a_line.setObjectName("a_line")
        self.verticalLayout_2.addWidget(self.a_line)
        self.a_name = QtWidgets.QLineEdit(self.widget)
        self.a_name.setWhatsThis("")
        self.a_name.setObjectName("a_name")
        self.verticalLayout_2.addWidget(self.a_name)
        self.exc_btn = QtWidgets.QPushButton(self.widget)
        self.exc_btn.setObjectName("exc_btn")
        self.verticalLayout_2.addWidget(self.exc_btn)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.data = QtWidgets.QLineEdit(self.widget)
        self.data.setObjectName("data")
        self.horizontalLayout_2.addWidget(self.data)
        self.save_btn = QtWidgets.QPushButton(self.widget)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "unit1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "unit2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "unit3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "unit4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "unit5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "unit6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "unit7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "unit8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        self.label_2.setText(_translate("MainWindow", "输入列数(数据的数量):"))
        self.label.setText(_translate("MainWindow", "输入行数(变量的数量):"))
        self.add_btn.setText(_translate("MainWindow", "create_list"))
        self.x_row.setText(_translate("MainWindow", "x行"))
        self.y_row.setText(_translate("MainWindow", "y行"))
        self.label_3.setText(_translate("MainWindow", "y="))
        self.rela_btn.setText(_translate("MainWindow", "calculate"))
        self.x_name.setText(_translate("MainWindow", "x名"))
        self.x_index.setText(_translate("MainWindow", "x行数"))
        self.y_name.setText(_translate("MainWindow", "y名"))
        self.y_index.setText(_translate("MainWindow", "y行数"))
        self.exam_num.setText(_translate("MainWindow", "保存图片名称"))
        self.anly_btn.setText(_translate("MainWindow", "draw"))
        self.a_line.setText(_translate("MainWindow", "输入行数"))
        self.a_name.setText(_translate("MainWindow", "输入变量名称"))
        self.exc_btn.setText(_translate("MainWindow", "change"))
        self.data.setText(_translate("MainWindow", "保存文件名"))
        self.save_btn.setText(_translate("MainWindow", "save"))
